COMMAND:
  COOLDOWN: "&cYou need to wait {cooldown} seconds to use this command."
  COOLDOWN_TIME: 60 #in seconds
  NO_PERMISSIONS: "&cYou dont have permissions to execute this command."

TYPE_MESSAGE:
  VIDEO:
    - ""
    - "&cType of url of your video"
    - "&cType &4&lCANCEL &cto cancel the process"
    - ""
  STREAM:
    - ""
    - "&cType of url of your stream"
    - "&cType &4&lCANCEL &cto cancel the process"
    - ""

URL_CHECKER:
  ERROR: "&cThat's not a url"

BROADCAST:
  MESSAGE:
    - ""
    - "&4&l{player} &cwants you to watch this {variant}"
    - "&4&l&n{url}"
    - ""

MENU:
  SELECTION_MENU:
    TITLE: "&cSelect an option"
    ROW_SIZE: 3
    HEADS:
      VIDEO:
        DISPLAYNAME: "&cNew Video"
        TEXTURE: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzQ4ODU0NWQ1N2M5ZWVkNTJjM2U1NDdlOTZjNDVkYWJiYjdjZjVmOThkNGM4ZmU2MWRjNmY2OWFiYTBhZWY5NiJ9fX0="
      STREAM:
        DISPLAYNAME: "&5New Stream"
        TEXTURE: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWQyYjA1YWJlNDk3NmMwYWYxZjU0YjhkMzRlNjU2ZDE0MzgzMTc0ZmY1YzZlYmE2MTNhOGE4NDA1NDk4Y2IxNSJ9fX0="

  CONFIRM_MENU:
    TITLE: "&cConfirm {variant}"
    ROW_SIZE: 3
    PROCESS_CANCELLED: "&cThe process has been cancelled"
    HEADS:
      CONFIRM:
        DISPLAYNAME: "&a&lCONFIRM"
        TEXTURE: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzNhYzdhZWE0MDJjZTYyOWE0ODMzYTQ1MjI4ZGY0NWE1MDYyZDExMmYwZjgyNmMzYzM0M2NmMDY4MDkxY2JlYSJ9fX0="
      CANCEL:
        DISPLAYNAME: "&c&lCANCEL"
        TEXTURE: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmM4ZmMzYTdjYTYwNTgzZmM2ZDQ4MTNlNDE0N2M1MmQzYTdmYzRiZDlmYjJlOGY3ZjIzYWU3YzMyZTRiM2U0In19fQ=="